### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by meixsh** [SengokuMedaru/nspj-AvantGuard#1]
hello, I have read a paper named AVANT-GUARD which is about implementing security SDN network by adding some new features into current OF switches and controller. So I just started searching for its open source implementation. So I met your project, but which made me doubt is what is your project doing, would you mind giving some materials and build steps for rookies. Which one is the most important is whether your project is relevant with me caring for. Because I hardly found some relations from your current project with that paper I have read.

**Comment by sansders** [comment]
> hello, I have read a paper named AVANT-GUARD which is about implementing security SDN network by adding some new features into current OF switches and controller. So I just started searching for its open source implementation. So I met your project, but which made me doubt is what is your project doing, would you mind giving some materials and build steps for rookies. Which one is the most important is whether your project is relevant with me caring for. Because I hardly found some relations from your current project with that paper I have read.

Hi, I believe you've got the wrong project. This is a project done as a submission for a polytechnic institution's module and is in no way affiliated with the paper you read.
